version: '3'

services:
  flask:
    build: ./app
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - vllm

  db:
    image: postgres:alpine
    container_name: postgresql_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_SERVER=db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  vllm:
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    container_name: vllm_container
    environment:
      - HF_TOKEN=${HF_TOKEN}
    ports:
      - "11434:11434"
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:

  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama_container
  #   ports:
  #     - "11434:11434"
  #   depends_on:
  #     - db